### ISSUE TITLE
checking inputs and returning nice error messages

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/saltbush#7]
a few ways to get it to error:
<img width="1176" alt="Screenshot 2024-11-19 at 5 50 36 pm" src="https://github.com/user-attachments/assets/44087cab-85e8-499d-832d-fa33e347978f">

**Comment by adelegem** [comment]
so first error is because if rarefaction is T it requires min_points and n.
second error is because min_points = 100 which is greater than the number of points in df_test.
i can add a line maybe that prints 'if rarefaction = T, add n and min_points' for first error and and 'min points must be <= the number of points in df' or something??

**Comment by wcornwell** [comment]
Yup. Just imagine you're a beginning saltbush user and trying to figure out the package. What kind of error message would be most useful?
